version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - .:/var/www

  nginx:
    build: ./docker/nginx
    container_name: docker.nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php
    ports:
      - "433:433"
      - "8000:80"
    networks:
      - docker.network
    volumes:
      - .:/var/www

  mysql:
    image: mysql:8
    container_name: docker.mysql
    restart: unless-stopped
    ports:
      - 33060:3306
    volumes:
      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_USER=root